stages:
  - test
  - build

.pytest:
  image: python:3.12
  stage: test
  before_script:
    - python3 -m pip install tox
  artifacts:
    when: always
    reports:
      junit: report.xml

pytest39:
  extends: .pytest
  image: python:3.9
  script:
    - tox run -e py39 -- --junitxml=report.xml 

pytest310:
  extends: .pytest
  image: python:3.10
  script:
    - tox run -e py310 -- --junitxml=report.xml 

pytest311:
  extends: .pytest
  image: python:3.11
  script:
    - tox run -e py311 -- --junitxml=report.xml 

pytest312:
  extends: .pytest
  image: python:3.12
  script:
    - tox run -e py312 -- --junitxml=report.xml 

pytest313:
  extends: .pytest
  image: python:3.13
  script:
    - tox run -e py313 -- --junitxml=report.xml 

pytest314:
  extends: .pytest
  image: python:3.14
  script:
    - apt update && apt install -y libglpk-dev swig gcc
    - tox run -e py314 -- --junitxml=report.xml 

build:
  image: python:3.12
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - python3 -m pip install tox
    - tox run -e build -- -p ${PYPI_API_TOKEN}

pages:
  image: python:3.12
  stage: build
  script:
  - pip install -U sphinx nbsphinx sphinx-autoapi
  - apt update && apt install -y pandoc
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  only:
  - master

